services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    image: airflowimage
    container_name: gemstone-prediction-airflow
    ports:
      - "8080:8080" #Airflow webserver
      - "5050:5050" #MLflow tracking server
    
  flaskapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flaskimage
    container_name: gemstone-prediction-app
    ports:
      - "3000:3000"