stages:
  data_ingestion:
    cmd: python src/gemstonePrediction/pipeline/training_pipeline.py data_ingestion
    deps:
      - src/gemstonePrediction/pipeline/training_pipeline.py
      - src/gemstonePrediction/components/data_ingestion.py

    outs:
      - artifacts/raw_data.csv
      - artifacts/test.csv
      - artifacts/train.csv

  data_transformation:
    cmd: python src/gemstonePrediction/pipeline/training_pipeline.py data_transformation
    deps:
      - src/gemstonePrediction/pipeline/training_pipeline.py
      - src/gemstonePrediction/components/data_transformation.py
      - artifacts/train.csv
      - artifacts/test.csv

    outs:
      - artifacts/preprocessor.pkl

  model_training:
    cmd: python src/gemstonePrediction/pipeline/training_pipeline.py model_training
    deps:
      - src/gemstonePrediction/pipeline/training_pipeline.py
      - src/gemstonePrediction/components/model_training.py
      - artifacts/preprocessor.pkl

    outs:
      - artifacts/model.pkl